// Example: public landing page (no auth). Generated by webtest-orch
// against a Next.js portfolio site. Demonstrates the issues[] collector
// pattern — every check goes into one array, the test fails ONCE at the
// end with the full picture.

import { test, expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';

test.describe('Landing public-site', () => {
  test('home page baseline', async ({ page }) => {
    const consoleErrors: string[] = [];
    const failedRequests: string[] = [];
    const issues: string[] = [];

    page.on('pageerror', (e) => consoleErrors.push(`pageerror: ${e.message}`));
    page.on('console', (m) => {
      if (m.type() === 'error') consoleErrors.push(`console: ${m.text()}`);
    });
    page.on('response', (r) => {
      if (r.status() >= 400 && !/\/(favicon|robots|sw\.js)/.test(r.url())) {
        failedRequests.push(`${r.status()} ${r.url()}`);
      }
    });
    page.on('requestfailed', (r) => {
      failedRequests.push(`fail ${r.url()} ${r.failure()?.errorText}`);
    });

    await page.goto('/');

    // Axe-core deterministic scan — every violation becomes one issue line.
    const a11y = await new AxeBuilder({ page })
      .withTags(['wcag2a', 'wcag2aa', 'wcag21aa', 'wcag22aa'])
      .analyze();
    a11y.violations.forEach((v) => {
      issues.push(`a11y[${v.impact}] ${v.id}: ${v.help} (${v.nodes.length}x nodes)`);
    });

    // Horizontal overflow check (mobile viewport common bug).
    const overflow = await page.evaluate(() => ({
      sw: document.documentElement.scrollWidth,
      cw: document.documentElement.clientWidth,
    }));
    if (overflow.sw > overflow.cw) {
      const vp = page.viewportSize();
      issues.push(`overflow: scroll @ ${vp?.width}px (sw=${overflow.sw}, cw=${overflow.cw})`);
    }

    // Heading hierarchy — h1 → h2 → h3, no skips of more than one level.
    const headings = await page.locator('h1,h2,h3,h4,h5,h6').evaluateAll((els) =>
      els.map((e) => ({
        level: parseInt(e.tagName[1]),
        text: (e.textContent || '').trim().slice(0, 50),
      })),
    );
    for (let i = 1; i < headings.length; i++) {
      if (headings[i].level - headings[i - 1].level > 1) {
        issues.push(
          `heading-jump: h${headings[i - 1].level}->h${headings[i].level} at "${headings[i].text}"`,
        );
      }
    }

    // Touch targets — WCAG 2.5.8 AA = 24x24 CSS px.
    const tooSmall = await page.locator('a, button, input, [role="button"]').evaluateAll((els) =>
      els
        .filter((e: Element) => {
          const r = (e as HTMLElement).getBoundingClientRect();
          return r.width > 0 && r.height > 0 && (r.width < 24 || r.height < 24);
        })
        .map((e: Element) => {
          const el = e as HTMLElement;
          const r = el.getBoundingClientRect();
          const text = (el.innerText || el.getAttribute('aria-label') || '').trim().slice(0, 25);
          return `${el.tagName}:"${text}" ${Math.round(r.width)}x${Math.round(r.height)}`;
        }),
    );
    tooSmall.forEach((t) => issues.push(`touch-target: ${t} (WCAG 2.5.8 needs 24x24)`));

    // Hard fail at end with FULL picture instead of stopping at the first miss.
    expect(
      issues,
      issues.length > 0 ? `${issues.length} issues found:\n  - ${issues.join('\n  - ')}` : '',
    ).toEqual([]);
    expect(consoleErrors, 'no uncaught console errors').toEqual([]);
    expect(failedRequests, 'no 4xx/5xx or net failures').toEqual([]);
  });
});
